export {
  CHAR_WIDTH_REM,
  FOOTER_SECTIONS,
  HOURS_IN_DAY,
  HTTP_METHODS,
  ISSUE_I18N_KEY,
  LANG_GEN,
  LANGUAGES,
  LINE_HEIGHT_REM,
  MINUTES_IN_HOUR,
  MS_IN_DAY,
  MS_IN_HOUR,
  MS_IN_MINUTE,
  MS_IN_SECOND,
  PADDING_REM,
  STATUS_CLIENT_ERROR,
  STATUS_INFO,
  STATUS_REDIRECT,
  STATUS_SERVER_ERROR,
  STATUS_SUCCESS,
  TABS,
  VARIABLE_REGEX,
} from "./globals";
export * from "./globals-animation";

export { ADVANCE_MS } from "./globals-tests";
