export {
  CHAR_WIDTH_REM,
  FOOTER_SECTIONS,
  HTTP_METHODS,
  ISSUE_I18N_KEY,
  LANG_GEN,
  LANGUAGES,
  LINE_HEIGHT_REM,
  MOCK_RESPONSE,
  PADDING_REM,
  TABS,
  VARIABLE_REGEX,
} from "./globals";
